services:
  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dockerdb
      SPRING_DATASOURCE_USERNAME: dockeruser
      SPRING_DATASOURCE_PASSWORD: dockerpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

    ports:
      - "8080:8080"
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: dockerdb
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dockerpassword
    ports:
      - "5432:5432"